# === UNIVERSAL MOULT TOOLKIT SYNTHESIS ===
# This script intersects the Global PC3 Drivers with the Conserved Venn Core 
# to identify the most robust, cross-species candidate genes for the article.

# === SETUP ===
if (file.exists("utils.R")) {
  source("utils.R")
} else if (file.exists(file.path("downstream_analysis", "utils.R"))) {
  source(file.path("downstream_analysis", "utils.R"))
}

log_header("Universal Moult Toolkit Synthesis")

# --- 1. LOAD COMBAT-CORRECTED DRIVERS (Global Signal) ---
# Generated by: combined_species_pca.R (all-OG analysis)
drivers_path <- file.path(get_project_root(), "PCA", "Combined", "top_2000", "Global_Drivers_ComBat_Corrected.csv")

if (!file.exists(drivers_path)) {
  stop("Corrected Global Drivers not found! Please run 'combined_species_pca.R' first.")
}

# PC Variance weights from the Combined PCA (Top 2000 OGs)
pc_weights <- c("PC1" = 21.1, "PC2" = 16.8)

# We load drivers for PC1 and PC2 and calculate the weighted Importance Score
global_drivers <- read_csv(drivers_path, show_col_types = FALSE) %>%
  filter(PC %in% names(pc_weights)) %>%
  mutate(importance_score = abs(Loading) * pc_weights[PC])

# --- 2. LOAD CONSERVED VENN CORE (Statistical Significance) ---
# Generated by: cross_species_core.R
core_path <- file.path("output_csv", "conserved_core_master_all_phases.csv")
if (!file.exists(core_path)) {
  stop("Conserved Core Master Table not found! Please run 'cross_species_core.R' first.")
}
venn_core <- read_csv(core_path, show_col_types = FALSE)

# --- 3. SYNTHESIS: FIND THE ROBUST INTERSECTION ---
cat("Intersecting Weighted Loadings with Conserved Venn Core and filtering for known genes...\n")

synthesis_table <- global_drivers %>%
  inner_join(venn_core, by = "Preferred_name") %>%
  # Filter out uncharacterized and hypothetical proteins for the main publication figure
  filter(!str_detect(Preferred_name, "(?i)uncharacterized|hypothetical")) %>%
  # If a gene is in both PC1 and PC2, keep the one with the higher importance score
  group_by(Preferred_name) %>%
  slice_max(importance_score, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  arrange(desc(importance_score))

cat("Found", nrow(synthesis_table), "genes that are BOTH Global PC1/PC2 Drivers and Statistically Conserved Core.\n")

# --- 4. CATEGORIZE CANDIDATES (Heuristic) ---
# This provides immediate functional grouping for the Results section.
synthesis_table <- synthesis_table %>%
  mutate(Category = case_when(
    str_detect(Preferred_name, "(?i)Chitin|Cuticle|Calc|Matrix") ~ "Structural/Cuticle",
    str_detect(Preferred_name, "(?i)Toxin|Antimicrobial|Defensin") ~ "Immunity/Protection",
    str_detect(Preferred_name, "(?i)Mucin|Ice") ~ "Lubrication/Desiccation",
    str_detect(Preferred_name, "(?i)Hormone|ECR|MIH|JHAMT") ~ "Regulation/Endocrine",
    TRUE ~ "Other/Metabolic"
  ))

# --- 5. SAVE FINAL ARTICLE DATA ---
output_file <- file.path("output_csv", "Universal_Moult_Toolkit_Candidates.csv")
write_csv(synthesis_table, output_file)

cat("\nTop 10 Universal Toolkit Candidates for the Paper:\n")
print(head(synthesis_table %>% select(Preferred_name, Loading, Phase, Category), 10))

cat("\nSynthesis complete! Data ready for Article drafting in:", output_file, "\n")
